### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by c00degrammer** [Forichok/TelegramOnlineSpy#1]
**heelo:")**
when i run spy.py with python3 see this:

```
Traceback (most recent call last):
  File "spy.py", line 22, in <module>
    client.connect()
  File "/home/abolfazl/.local/lib/python3.6/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/abolfazl/.local/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py", line 445, in connect
    proxy=self._proxy
  File "/home/abolfazl/.local/lib/python3.6/site-packages/telethon/network/connection/tcpmtproxy.py", line 101, in __init__
    self._secret = bytes.fromhex(proxy[2])
ValueError: non-hexadecimal number found in fromhex() arg at position 1
```

**Comment by Forichok** [comment]
try to disable proxy in code
