### ISSUE TITLE
Error message when target user online

### ISSUE THREAD

**Issue by koxle** [Forichok/TelegramOnlineSpy#25]
```
Unhandled exception on start
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "spy.py", line 146, in start
    await event.respond(f'{get_interval(was_offline)}: {contact.name} went online.')
  File "spy.py", line 289, in get_interval
    d = divmod(date.total_seconds(),86400)  # days
AttributeError: 'str' object has no attribute 'total_seconds'

```

How can I resolve it? 
When the target user online, this error will appear and freeze the monitoring process

**Comment by koxle** [comment]
I am using python3.7.4
Running on CentOS 7

**Comment by lauriolasw** [comment]
Up
